
spring:
  application:
   name: "diplomado-kafka-inventory-consumer"
# DataSource settings
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/restaurant_registry"
    username: "postgres"
    password: "empanada123"
# Hibernate settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:  "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
  server:
    port: 8081

application:
  kafka:
    host: ${KAFKA_HOST:localhost}
    port: ${KAFKA_PORT:9092}
